{"name": "test_login_with_valid_email_and_invalid_password_Duplicate", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <Tests.test_Login(duplicate).TestPanarayLoginDuplicate object at 0x00000215002B5A50>\n\n    def test_login_with_valid_email_and_invalid_password_Duplicate(self):\n        login = Login_Page(self.driver)\n        login.login_with_credentials(login.valid_email, self.fake_password())\n        login.display_error_msg()\n        expected_error_msg = \"Email or Password not recognized, try again.1111\"\n>       login.assert_error_msg(expected_error_msg)\n\nTests\\test_Login(duplicate).py:26: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Pages.Login_Page.Login_Page object at 0x0000021500801050>, expected_text = 'Email or Password not recognized, try again.1111'\n\n    def assert_error_msg(self, expected_text):\n        message = self.driver.find_element(By.XPATH, self.error_message_locator).text\n>       assert message == expected_text\nE       AssertionError\n\nPages\\Login_Page.py:34: AssertionError"}, "start": 1695667565279, "stop": 1695667568221, "uuid": "4a3d6e48-62e8-4cda-a496-799ba5cb0ffc", "historyId": "9581a2f8ea7f6829aae721e266b65c65", "testCaseId": "9581a2f8ea7f6829aae721e266b65c65", "fullName": "Tests.test_Login(duplicate).TestPanarayLoginDuplicate#test_login_with_valid_email_and_invalid_password_Duplicate", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_Login(duplicate)"}, {"name": "subSuite", "value": "TestPanarayLoginDuplicate"}, {"name": "host", "value": "WONIT11L32CV6Z"}, {"name": "thread", "value": "23692-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_Login(duplicate)"}]}