{"name": "test_login_with_invalid_credentials_Duplicate", "status": "passed", "start": 1695710966757, "stop": 1695710969129, "uuid": "124eafc6-7b17-4779-8444-d0ea61cd5cb1", "historyId": "7aa590b2f4b1e5d028e013fb53ecb39d", "testCaseId": "7aa590b2f4b1e5d028e013fb53ecb39d", "fullName": "Tests.test_Login(duplicate).TestPanarayLoginDuplicate#test_login_with_invalid_credentials_Duplicate", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_Login(duplicate)"}, {"name": "subSuite", "value": "TestPanarayLoginDuplicate"}, {"name": "host", "value": "WONIT11L32CV6Z"}, {"name": "thread", "value": "21668-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_Login(duplicate)"}]}