{"name": "test_login_with_invalid_credentials_Duplicate", "status": "passed", "start": 1695709720279, "stop": 1695709723364, "uuid": "4ee366b0-2a17-4cf7-95e9-4f7dfc7493fe", "historyId": "7aa590b2f4b1e5d028e013fb53ecb39d", "testCaseId": "7aa590b2f4b1e5d028e013fb53ecb39d", "fullName": "Tests.test_Login(duplicate).TestPanarayLoginDuplicate#test_login_with_invalid_credentials_Duplicate", "labels": [{"name": "tag", "value": "@pytest.mark.usefixtures('setup_and_teardown', 'log_on_failure')"}, {"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_Login(duplicate)"}, {"name": "subSuite", "value": "TestPanarayLoginDuplicate"}, {"name": "host", "value": "WONIT11L32CV6Z"}, {"name": "thread", "value": "12312-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_Login(duplicate)"}]}